// <auto-generated />
using System;
using ECommerceTessa.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceTessa.Infraestructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201124015524_v1.0")]
    partial class v10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Apple")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Departament")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("Floor")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("House")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Lot")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Number")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Observation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("PostalCode")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ErasedState = false,
                            Name = "Victoria's Secret"
                        },
                        new
                        {
                            Id = 2L,
                            ErasedState = false,
                            Name = "La Perla"
                        },
                        new
                        {
                            Id = 3L,
                            ErasedState = false,
                            Name = "Agent Provocateur"
                        },
                        new
                        {
                            Id = 4L,
                            ErasedState = false,
                            Name = "Oysho"
                        },
                        new
                        {
                            Id = 5L,
                            ErasedState = false,
                            Name = "H&M"
                        },
                        new
                        {
                            Id = 6L,
                            ErasedState = false,
                            Name = "E-Lakokette"
                        },
                        new
                        {
                            Id = 7L,
                            ErasedState = false,
                            Name = "Botica Lingerie"
                        },
                        new
                        {
                            Id = 8L,
                            ErasedState = false,
                            Name = "Pleasurements"
                        },
                        new
                        {
                            Id = 9L,
                            ErasedState = false,
                            Name = " Journelle"
                        });
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ErasedState = false,
                            Name = "Bikinis"
                        },
                        new
                        {
                            Id = 2L,
                            ErasedState = false,
                            Name = "Conjuntos"
                        },
                        new
                        {
                            Id = 3L,
                            ErasedState = false,
                            Name = "Enterizas"
                        },
                        new
                        {
                            Id = 4L,
                            ErasedState = false,
                            Name = "Bodys"
                        },
                        new
                        {
                            Id = 5L,
                            ErasedState = false,
                            Name = "Bombachas"
                        });
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Cloudinary.ProductPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPhotos");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Colour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "San Salvador De Jujuy",
                            ErasedState = false,
                            ProvinceId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Humahuaca",
                            ErasedState = false,
                            ProvinceId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Salta",
                            ErasedState = false,
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Rosario De La Frontera",
                            ErasedState = false,
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Formosa",
                            ErasedState = false,
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Bermejo",
                            ErasedState = false,
                            ProvinceId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Resistencia",
                            ErasedState = false,
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Almirante Brown",
                            ErasedState = false,
                            ProvinceId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "San Fernando Del Valle De Catamarca",
                            ErasedState = false,
                            ProvinceId = 5L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Andalgala",
                            ErasedState = false,
                            ProvinceId = 5L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "San Miguel De Tucuman",
                            ErasedState = false,
                            ProvinceId = 6L
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Yerba Buena",
                            ErasedState = false,
                            ProvinceId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Santiago Del Estero",
                            ErasedState = false,
                            ProvinceId = 7L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "La Banda",
                            ErasedState = false,
                            ProvinceId = 7L
                        },
                        new
                        {
                            Id = 15L,
                            Description = "Corrientes",
                            ErasedState = false,
                            ProvinceId = 8L
                        },
                        new
                        {
                            Id = 16L,
                            Description = "Bella Vista",
                            ErasedState = false,
                            ProvinceId = 8L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "Posadas",
                            ErasedState = false,
                            ProvinceId = 9L
                        },
                        new
                        {
                            Id = 18L,
                            Description = "Iguazu",
                            ErasedState = false,
                            ProvinceId = 9L
                        },
                        new
                        {
                            Id = 19L,
                            Description = "San Juan",
                            ErasedState = false,
                            ProvinceId = 10L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Valle Fertil",
                            ErasedState = false,
                            ProvinceId = 10L
                        },
                        new
                        {
                            Id = 21L,
                            Description = "La Rioja",
                            ErasedState = false,
                            ProvinceId = 11L
                        },
                        new
                        {
                            Id = 22L,
                            Description = "Arauco",
                            ErasedState = false,
                            ProvinceId = 11L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Cordoba",
                            ErasedState = false,
                            ProvinceId = 12L
                        },
                        new
                        {
                            Id = 24L,
                            Description = "Cruz Del Eje",
                            ErasedState = false,
                            ProvinceId = 12L
                        },
                        new
                        {
                            Id = 25L,
                            Description = "Santa Fe",
                            ErasedState = false,
                            ProvinceId = 13L
                        },
                        new
                        {
                            Id = 26L,
                            Description = "Santo Tome",
                            ErasedState = false,
                            ProvinceId = 13L
                        },
                        new
                        {
                            Id = 27L,
                            Description = "Mendoza",
                            ErasedState = false,
                            ProvinceId = 14L
                        },
                        new
                        {
                            Id = 28L,
                            Description = "Uspallata",
                            ErasedState = false,
                            ProvinceId = 14L
                        },
                        new
                        {
                            Id = 29L,
                            Description = "San Luis",
                            ErasedState = false,
                            ProvinceId = 15L
                        },
                        new
                        {
                            Id = 30L,
                            Description = "Chacabuco",
                            ErasedState = false,
                            ProvinceId = 15L
                        },
                        new
                        {
                            Id = 31L,
                            Description = "Neuquen",
                            ErasedState = false,
                            ProvinceId = 16L
                        },
                        new
                        {
                            Id = 32L,
                            Description = "Los Lagos",
                            ErasedState = false,
                            ProvinceId = 16L
                        },
                        new
                        {
                            Id = 33L,
                            Description = "Santa Rosa",
                            ErasedState = false,
                            ProvinceId = 17L
                        },
                        new
                        {
                            Id = 34L,
                            Description = "Trenel",
                            ErasedState = false,
                            ProvinceId = 17L
                        },
                        new
                        {
                            Id = 35L,
                            Description = "Caba",
                            ErasedState = false,
                            ProvinceId = 18L
                        },
                        new
                        {
                            Id = 36L,
                            Description = "La Plata",
                            ErasedState = false,
                            ProvinceId = 18L
                        },
                        new
                        {
                            Id = 37L,
                            Description = "Viedma",
                            ErasedState = false,
                            ProvinceId = 19L
                        },
                        new
                        {
                            Id = 38L,
                            Description = "Las Grutas",
                            ErasedState = false,
                            ProvinceId = 19L
                        },
                        new
                        {
                            Id = 39L,
                            Description = "Rawson",
                            ErasedState = false,
                            ProvinceId = 20L
                        },
                        new
                        {
                            Id = 40L,
                            Description = "Sarmiento",
                            ErasedState = false,
                            ProvinceId = 20L
                        },
                        new
                        {
                            Id = 41L,
                            Description = "Rio Gallegos",
                            ErasedState = false,
                            ProvinceId = 21L
                        },
                        new
                        {
                            Id = 42L,
                            Description = "Rio Chico",
                            ErasedState = false,
                            ProvinceId = 21L
                        },
                        new
                        {
                            Id = 43L,
                            Description = "Usuahia",
                            ErasedState = false,
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 44L,
                            Description = "Rio Grande",
                            ErasedState = false,
                            ProvinceId = 2L
                        },
                        new
                        {
                            Id = 45L,
                            Description = "Parana",
                            ErasedState = false,
                            ProvinceId = 23L
                        },
                        new
                        {
                            Id = 46L,
                            Description = "Concordia",
                            ErasedState = false,
                            ProvinceId = 23L
                        });
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Movement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<long>("VoucherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("bigint");

                    b.Property<long>("Cuil")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Price", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<decimal>("NominalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PromotionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<bool>("DiscountStock")
                        .HasColumnType("bit");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ShowBrand")
                        .HasColumnType("bit");

                    b.Property<bool>("Slow")
                        .HasColumnType("bit");

                    b.Property<int>("Stock1")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Jujuy",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Salta",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Formosa",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Chaco",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Catamarca",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Tucuman",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Santiago Del Estero",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Corrientes",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Misiones",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 10L,
                            Description = "San Juan",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 11L,
                            Description = "La Rioja",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Cordoba",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Santa Fe",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 14L,
                            Description = "Mendoza",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 15L,
                            Description = "San Luis",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 16L,
                            Description = "Neuquen",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 17L,
                            Description = "La Pampa",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 18L,
                            Description = "Buenos Aires",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 19L,
                            Description = "Rio Negro",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Chubut",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 21L,
                            Description = "Santa Cruz",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 22L,
                            Description = "Tierra Del Fuego",
                            ErasedState = false
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Entre Rios",
                            ErasedState = false
                        });
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Stock", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("WayToPay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Waist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("ColourId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("ErasedState")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ColourId");

                    b.ToTable("Waists");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("ECommerceTessa.Domain.Entities.Person");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Address", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Location", "Location")
                        .WithMany("Addresses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceTessa.Domain.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId");

                    b.Navigation("Location");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Cloudinary.ProductPhoto", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Colour", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Product", "Product")
                        .WithMany("Colour")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Location", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Province", "Province")
                        .WithMany("Locations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Movement", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Voucher", "Voucher")
                        .WithMany("Movements")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Price", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Product", "Product")
                        .WithOne("Price")
                        .HasForeignKey("ECommerceTessa.Domain.Entities.Price", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceTessa.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Stock", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Waist", "Waist")
                        .WithOne("Stock")
                        .HasForeignKey("ECommerceTessa.Domain.Entities.Stock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waist");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.User", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Person", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.User", "User")
                        .WithMany("Vouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Waist", b =>
                {
                    b.HasOne("ECommerceTessa.Domain.Entities.Colour", "Colour")
                        .WithMany("Waists")
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Colour", b =>
                {
                    b.Navigation("Waists");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Location", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Product", b =>
                {
                    b.Navigation("Colour");

                    b.Navigation("Price");

                    b.Navigation("ProductPhotos");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Province", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.User", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Voucher", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("ECommerceTessa.Domain.Entities.Waist", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
